print('사용자 정보를 입력하세요.')
userName = input('이름: ')
userPhone = input('전화번호: ')
userMail = input('메일: ')
userJob = input('직업')
print('------------------------')
print('이름: ' + userName)
print('전화번호: ' + userPhone)
print('메일: ' + userMail)
print('직업: ' + userJob)
print('------------------------')
